### ISSUE TITLE
GMoE实验的Evaluation

### ISSUE THREAD

**Issue by sharkdrop** [LINs-lab/DynMoE#1]
作者您好，最近我在尝试复现GMoE的实验结果，按照您提供的run_scripts，我在office_home上跑了四个test_env和3个seed的实验，但在evaluation上遇到了问题。

我尝试按照您提供的python3 -m domainbed.scripts.collect_results --input_dir=${output_dir}来进行evaluation，但得到的输出文件是

![1727071225635](https://github.com/user-attachments/assets/4b9fff4c-0532-4906-bb58-36f39ed6373d)

是哪里出了问题吗

**Comment by QAQdev** [comment]
这个看起来像是--input_dir没有设置正确，可以提供一下您GMoE输出checkpoint的目录结构吗？

**Comment by sharkdrop** [comment]
这是目录结构，input_dir设置为./output-vanilla：
![image](https://github.com/user-attachments/assets/a97b062e-b78b-4dc9-aa9d-565db886ad63)

得到的result.txt为：
![image](https://github.com/user-attachments/assets/b412a20a-22fa-4152-9516-796e9626968b)

**Comment by gyxxyg** [comment]
可以尝试把input_dir设置为./output-vanilla/PACS。具体使用方法可以参考https://github.com/facebookresearch/DomainBed，GMoE的代码主要是基于DomainBed修改的，evaluation部分是一致的。

**Comment by sharkdrop** [comment]
> 可以尝试把input_dir设置为./output-vanilla/PACS。具体使用方法可以参考[DomainBed](https://github.com/facebookresearch/DomainBed)，GMoE的代码主要是基于DomainBed修改的，evaluation部分是一致的。

感谢，已经可以正常进行evaluation了，不知道能否提供一下虚拟环境的yaml文件，想对齐一下虚拟环境的配置。
