### ISSUE TITLE
MoE-LLaVA实验的llava-bench-in-the-wild的evaluation

### ISSUE THREAD

**Issue by sharkdrop** [LINs-lab/DynMoE#2]
作者，您好，关于llava-bench-in-the-wild的evaluation，使用的gpt_model是gpt-3.5-turbo还是其他模型啊

**Comment by QAQdev** [comment]
您好，感谢您的关注。我们在所有需要gpt评估的benchmark上均使用gpt-3.5-turbo

**Comment by sharkdrop** [comment]
感谢您的及时回复，那么对于如下evaluation结果，表格中汇报的是哪个值啊：
![image](https://github.com/user-attachments/assets/7f4f731d-a558-4d15-9e78-7e258485531d)

**Comment by sharkdrop** [comment]
感谢！
